name: ROSLauncher
on: [push]
jobs:
  testing:
    runs-on: windows-latest
    name: ROS Launcher Testing
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - uses: Gr1N/setup-poetry@v7
      - name: Fetch Discord SDK
        run: |
          choco install wget -y
          wget https://dl-game-sdk.discordapp.net/2.5.6/discord_game_sdk.zip
          unzip discord_game_sdk.zip -d discord_game_sdk
          mkdir lib
          cp discord_game_sdk/lib/x86_64/discord_game_sdk.dll lib/
          rm -rf discord_game_sdk*
        shell: bash

      - name: Build application
        run: |
          LC_ALL="UTF-8" LC_CTYPE="UTF-8" poetry install
          SITE_PACKAGES=$(poetry run python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])') \
          poetry run pyinstaller -F --noconsole --paths=$SITE_PACKAGES --icon='img/ROSLauncher.ico' --clean ros_launcher.py
        shell: bash

      - name: Get ROS
        run: |
          wget https://github.com/AlbertBall/railway-dot-exe/releases/download/v2.11.1/Release.v2.11.1.zip
          unzip Release.v2.11.1.zip
          mkdir Release.v2.11.1/Railway/DiscordLauncher
          mv lib Release.v2.11.1/Railway/DiscordLauncher
          mv dist/ros_launcher.exe Release.v2.11.1/Railway/DiscordLauncher
        shell: bash

      - name: Test application
        run: ./Release.v2.11.1/Railway/DiscordLauncher/ros_launcher.exe
        shell: bash
